package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"io"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// getTypeName extracts the unqualified short name from a *types.Named.
// Returns "" for non-named types.
func getTypeName(typ types.Type) string {
	named, ok := typ.(*types.Named)
	if !ok {
		return ""
	}
	return named.Obj().Name()
}

// mapToGoLit converts a Go value (map[string]any, []any, []string, or primitive)
// to a Go source literal string suitable for embedding in generated code.
func mapToGoLit(v any) string {
	switch val := v.(type) {
	case nil:
		return "nil"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case string:
		return fmt.Sprintf("%q", val)
	case float64:
		if math.IsNaN(val) {
			return "0"
		}
		if math.IsInf(val, 0) {
			if val > 0 {
				return "math.MaxFloat64"
			}
			return "-math.MaxFloat64"
		}
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return strconv.FormatFloat(val, 'f', -1, 64)
	case float32:
		v := float64(val)
		if math.IsNaN(v) {
			return "0"
		}
		if math.IsInf(v, 0) {
			if v > 0 {
				return "math.MaxFloat32"
			}
			return "-math.MaxFloat32"
		}
		return strconv.FormatFloat(v, 'f', -1, 32)
	case int:
		return fmt.Sprintf("%d", val)
	case int64:
		return fmt.Sprintf("%d", val)
	case []string:
		if len(val) == 0 {
			return "[]string{}"
		}
		parts := make([]string, len(val))
		for i, s := range val {
			parts[i] = fmt.Sprintf("%q", s)
		}
		return "[]string{" + strings.Join(parts, ", ") + "}"
	case []any:
		if len(val) == 0 {
			return "[]any{}"
		}
		parts := make([]string, len(val))
		for i, item := range val {
			parts[i] = mapToGoLit(item)
		}
		return "[]any{" + strings.Join(parts, ", ") + "}"
	case map[string]any:
		if len(val) == 0 {
			return "map[string]any{}"
		}
		keys := make([]string, 0, len(val))
		for k := range val {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var b strings.Builder
		b.WriteString("map[string]any{\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "%q: %s,\n", k, mapToGoLit(val[k]))
		}
		b.WriteString("}")
		return b.String()
	default:
		return fmt.Sprintf("%v", v)
	}
}

// emitMethod holds pre-computed data for a single method, used by the template.
type emitMethod struct {
	ToolName string
	GoName   string
	Desc     string
	ReqType  string // short type name (e.g., "GetWeatherRequest")
	Schema   string // rendered Go map literal of the JSON schema
}

// emitData is the template data struct.
type emitData struct {
	PkgName string
	SvcName string
	Methods []emitMethod
}

const genFileHeader = "// Code generated by llm-tools. DO NOT EDIT.\n"

var genTmpl = template.Must(template.New("gen").Funcs(template.FuncMap{
	"backtick": func() string { return "`" },
}).Parse(genFileHeader + `
package {{.PkgName}}

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/code-koan/llm-sdk-go/providers"
)

// ---- Tools ----

// {{.SvcName}}Tools returns tool definitions for {{.SvcName}}.
func {{.SvcName}}Tools() []providers.Tool {
	return []providers.Tool{
		{{- range .Methods }}
		{
			Type: "function",
			Function: providers.Function{
				Name:        {{.ToolName | printf "%q"}},
				Description: {{.Desc | printf "%q"}},
				Parameters:  {{.Schema}},
			},
		},
		{{- end }}
	}
}

// ---- Dispatch ----

// {{.SvcName}}Handler dispatches tool calls to a {{.SvcName}} implementation.
type {{.SvcName}}Handler struct {
	Impl {{.SvcName}}
}

// Execute handles a tool call by name.
func (h *{{.SvcName}}Handler) Execute(
	ctx context.Context, name string, arguments json.RawMessage,
) (string, error) {
	switch name {
	{{- range .Methods }}
	case {{.ToolName | printf "%q"}}:
		var req {{.ReqType}}
		if err := json.Unmarshal(arguments, &req); err != nil {
			return "", fmt.Errorf("%s: %w", {{.ToolName | printf "%q"}}, err)
		}
		resp, err := h.Impl.{{.GoName}}(ctx, req)
		if err != nil {
			return "", fmt.Errorf("%s: %w", {{.ToolName | printf "%q"}}, err)
		}
		data, err := json.Marshal(resp)
		if err != nil {
			return "", fmt.Errorf("%s: marshal: %w", {{.ToolName | printf "%q"}}, err)
		}
		return string(data), nil
	{{- end }}
	default:
		return "", fmt.Errorf("unknown tool: %s", name)
	}
}

// ---- MCP ----

// MCPToolsList returns the MCP tools/list response.
func (h *{{.SvcName}}Handler) MCPToolsList() []map[string]any {
	return []map[string]any{
		{{- range .Methods }}
		{
			"name":        {{.ToolName | printf "%q"}},
			"description": {{.Desc | printf "%q"}},
			"inputSchema": {{.Schema}},
		},
		{{- end }}
	}
}

// MCPToolsCall handles an MCP tools/call request.
func (h *{{.SvcName}}Handler) MCPToolsCall(
	ctx context.Context, name string, arguments json.RawMessage,
) (*MCPCallResult, error) {
	result, err := h.Execute(ctx, name, arguments)
	if err != nil {
		return &MCPCallResult{
			IsError: true,
			Content: []MCPContent{{"{{"}}Type: "text", Text: err.Error(){{"}}"}},
		}, nil
	}
	return &MCPCallResult{
		Content: []MCPContent{{"{{"}}Type: "text", Text: result{{"}}"}},
	}, nil
}

// MCPCallResult is the result of an MCP tools/call.
type MCPCallResult struct {
	Content []MCPContent {{backtick}}json:"content"{{backtick}}
	IsError bool         {{backtick}}json:"isError,omitempty"{{backtick}}
}

// MCPContent is a content item in an MCP call result.
type MCPContent struct {
	Type string {{backtick}}json:"type"{{backtick}}
	Text string {{backtick}}json:"text,omitempty"{{backtick}}
}

// MCPHandler returns an http.Handler serving MCP JSON-RPC 2.0 tools/list and tools/call.
func (h *{{.SvcName}}Handler) MCPHandler() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("POST /tools/list", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		tools := h.MCPToolsList()
		_ = json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"id":      1,
			"result": map[string]any{
				"tools": tools,
			},
		})
	})

	mux.HandleFunc("POST /tools/call", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")

		var mcpReq struct {
			JSONRPC string {{backtick}}json:"jsonrpc"{{backtick}}
			ID      any    {{backtick}}json:"id"{{backtick}}
			Method  string {{backtick}}json:"method"{{backtick}}
			Params  struct {
				Name      string          {{backtick}}json:"name"{{backtick}}
				Arguments json.RawMessage {{backtick}}json:"arguments"{{backtick}}
			} {{backtick}}json:"params"{{backtick}}
		}

		if err := json.NewDecoder(r.Body).Decode(&mcpReq); err != nil {
			_ = json.NewEncoder(w).Encode(map[string]any{
				"jsonrpc": "2.0",
				"id":      nil,
				"error": map[string]any{
					"code":    -32700,
					"message": "Parse error",
				},
			})
			return
		}

		result, _ := h.MCPToolsCall(r.Context(), mcpReq.Params.Name, mcpReq.Params.Arguments)

		_ = json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"id":      mcpReq.ID,
			"result":  result,
		})
	})

	return mux
}
`))

// Generate writes the .gen.go file for the service to w.
func Generate(w io.Writer, pkgName string, svc *ServiceInfo) error {
	// Build template data.
	methods := make([]emitMethod, len(svc.Methods))
	for i, m := range svc.Methods {
		reqTypeName := getTypeName(m.ReqType)
		if reqTypeName == "" {
			return fmt.Errorf("method %s: request type must be a named type", m.GoName)
		}
		schema := GenerateSchema(m.ReqType, m.FieldComments)
		methods[i] = emitMethod{
			ToolName: m.ToolName,
			GoName:   m.GoName,
			Desc:     m.Desc,
			ReqType:  reqTypeName,
			Schema:   mapToGoLit(schema),
		}
	}

	data := emitData{
		PkgName: pkgName,
		SvcName: svc.Name,
		Methods: methods,
	}

	var buf bytes.Buffer
	if err := genTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template execute: %w", err)
	}

	// Format the generated Go source.
	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("go format: %w", err)
	}

	if _, err := w.Write(formatted); err != nil {
		return fmt.Errorf("write: %w", err)
	}

	return nil
}

// GenerateFile writes the .gen.go file to the specified path.
// outputPath is the full path for the output .gen.go file.
func GenerateFile(outputPath string, pkgName string, svc *ServiceInfo) error {
	dir := filepath.Dir(outputPath)
	tmp, err := os.CreateTemp(dir, ".gen-*.go")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if err := Generate(tmp, pkgName, svc); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}

	if err := os.Rename(tmpName, outputPath); err != nil {
		return fmt.Errorf("rename: %w", err)
	}
	return nil
}
