// Code generated by llm-tools. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/code-koan/llm-sdk-go/providers"
)

// ---- Tools ----

// WeatherServiceTools returns tool definitions for WeatherService.
func WeatherServiceTools() []providers.Tool {
	return []providers.Tool{
		{
			Type: "function",
			Function: providers.Function{
				Name:        "get_weather",
				Description: "Get the current weather for a location",
				Parameters: map[string]any{
					"properties": map[string]any{
						"location": map[string]any{
							"description": "Location is the city or region to get weather for.",
							"type":        "string",
						},
						"unit": map[string]any{
							"description": "Unit is the temperature unit.",
							"enum":        []string{"celsius", "fahrenheit"},
							"type":        "string",
						},
					},
					"required": []string{"location"},
					"type":     "object",
				},
			},
		},
		{
			Type: "function",
			Function: providers.Function{
				Name:        "calculate",
				Description: "Perform a mathematical calculation",
				Parameters: map[string]any{
					"properties": map[string]any{
						"a": map[string]any{
							"description": "A is the first operand.",
							"type":        "number",
						},
						"b": map[string]any{
							"description": "B is the second operand.",
							"type":        "number",
						},
						"operation": map[string]any{
							"description": "Operation is the arithmetic operation: add, subtract, multiply, divide.",
							"type":        "string",
						},
					},
					"required": []string{"operation", "a", "b"},
					"type":     "object",
				},
			},
		},
	}
}

// ---- Dispatch ----

// WeatherServiceHandler dispatches tool calls to a WeatherService implementation.
type WeatherServiceHandler struct {
	Impl WeatherService
}

// Execute handles a tool call by name.
func (h *WeatherServiceHandler) Execute(
	ctx context.Context, name string, arguments json.RawMessage,
) (string, error) {
	switch name {
	case "get_weather":
		var req GetWeatherRequest
		if err := json.Unmarshal(arguments, &req); err != nil {
			return "", fmt.Errorf("%s: %w", "get_weather", err)
		}
		resp, err := h.Impl.GetWeather(ctx, req)
		if err != nil {
			return "", fmt.Errorf("%s: %w", "get_weather", err)
		}
		data, err := json.Marshal(resp)
		if err != nil {
			return "", fmt.Errorf("%s: marshal: %w", "get_weather", err)
		}
		return string(data), nil
	case "calculate":
		var req CalculateRequest
		if err := json.Unmarshal(arguments, &req); err != nil {
			return "", fmt.Errorf("%s: %w", "calculate", err)
		}
		resp, err := h.Impl.Calculate(ctx, req)
		if err != nil {
			return "", fmt.Errorf("%s: %w", "calculate", err)
		}
		data, err := json.Marshal(resp)
		if err != nil {
			return "", fmt.Errorf("%s: marshal: %w", "calculate", err)
		}
		return string(data), nil
	default:
		return "", fmt.Errorf("unknown tool: %s", name)
	}
}

// ---- MCP ----

// MCPToolsList returns the MCP tools/list response.
func (h *WeatherServiceHandler) MCPToolsList() []map[string]any {
	return []map[string]any{
		{
			"name":        "get_weather",
			"description": "Get the current weather for a location",
			"inputSchema": map[string]any{
				"properties": map[string]any{
					"location": map[string]any{
						"description": "Location is the city or region to get weather for.",
						"type":        "string",
					},
					"unit": map[string]any{
						"description": "Unit is the temperature unit.",
						"enum":        []string{"celsius", "fahrenheit"},
						"type":        "string",
					},
				},
				"required": []string{"location"},
				"type":     "object",
			},
		},
		{
			"name":        "calculate",
			"description": "Perform a mathematical calculation",
			"inputSchema": map[string]any{
				"properties": map[string]any{
					"a": map[string]any{
						"description": "A is the first operand.",
						"type":        "number",
					},
					"b": map[string]any{
						"description": "B is the second operand.",
						"type":        "number",
					},
					"operation": map[string]any{
						"description": "Operation is the arithmetic operation: add, subtract, multiply, divide.",
						"type":        "string",
					},
				},
				"required": []string{"operation", "a", "b"},
				"type":     "object",
			},
		},
	}
}

// MCPToolsCall handles an MCP tools/call request.
func (h *WeatherServiceHandler) MCPToolsCall(
	ctx context.Context, name string, arguments json.RawMessage,
) (*MCPCallResult, error) {
	result, err := h.Execute(ctx, name, arguments)
	if err != nil {
		return &MCPCallResult{
			IsError: true,
			Content: []MCPContent{{Type: "text", Text: err.Error()}},
		}, nil
	}
	return &MCPCallResult{
		Content: []MCPContent{{Type: "text", Text: result}},
	}, nil
}

// MCPCallResult is the result of an MCP tools/call.
type MCPCallResult struct {
	Content []MCPContent `json:"content"`
	IsError bool         `json:"isError,omitempty"`
}

// MCPContent is a content item in an MCP call result.
type MCPContent struct {
	Type string `json:"type"`
	Text string `json:"text,omitempty"`
}

// MCPHandler returns an http.Handler serving MCP JSON-RPC 2.0 tools/list and tools/call.
func (h *WeatherServiceHandler) MCPHandler() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("POST /tools/list", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		tools := h.MCPToolsList()
		_ = json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"id":      1,
			"result": map[string]any{
				"tools": tools,
			},
		})
	})

	mux.HandleFunc("POST /tools/call", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")

		var mcpReq struct {
			JSONRPC string `json:"jsonrpc"`
			ID      any    `json:"id"`
			Method  string `json:"method"`
			Params  struct {
				Name      string          `json:"name"`
				Arguments json.RawMessage `json:"arguments"`
			} `json:"params"`
		}

		if err := json.NewDecoder(r.Body).Decode(&mcpReq); err != nil {
			_ = json.NewEncoder(w).Encode(map[string]any{
				"jsonrpc": "2.0",
				"id":      nil,
				"error": map[string]any{
					"code":    -32700,
					"message": "Parse error",
				},
			})
			return
		}

		result, _ := h.MCPToolsCall(r.Context(), mcpReq.Params.Name, mcpReq.Params.Arguments)

		_ = json.NewEncoder(w).Encode(map[string]any{
			"jsonrpc": "2.0",
			"id":      mcpReq.ID,
			"result":  result,
		})
	})

	return mux
}
